# **NumPy: Esempi e Test Interattivi**

Questo notebook contiene esempi pratici su NumPy con test e commenti.

Esegui ogni cella per vedere il comportamento delle operazioni di NumPy.

In [1]:
import numpy as np
import ipywidgets as widgets
from IPython.display import display

NumPy è il cuore numerico di Python.

È ottimizzato per il calcolo scientifico e matematico su array multidimensionali.



📌 Perché è più veloce?
Gli array NumPy (ndarray) sono contigui in memoria e sfruttano istruzioni vettoriali (SIMD).

Invece, le liste Python sono oggetti eterogenei gestiti in modo più flessibile ma molto più lento.



Codice di confronto: lista vs NumPy


In [3]:
import numpy as np

# Somma tra due liste Python
lista1 = list(range(1000000))
lista2 = list(range(1000000))

%timeit [x + y for x, y in zip(lista1, lista2)]


58.7 ms ± 3.05 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
# Somma tra due array NumPy
array1 = np.arange(1000000)
array2 = np.arange(1000000)

%timeit array1 + array2


1.23 ms ± 13.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## **1. Creazione di Array**
Esempi di creazione di array NumPy.

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
print("Array 1D:", arr1)

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("Array 2D:", arr2)

arr3 = np.zeros((3,3))
print("Matrice di zeri:", arr3)

arr4 = np.ones((2,2))
print("Matrice di uni:", arr4)

arr5 = np.arange(0, 10, 2)
print("Array con step 2:", arr5)

arr6 = np.linspace(0, 5, 10)
print("Array con 10 valori equidistanti:", arr6)

Array 1D: [1 2 3 4 5]
Array 2D: [[1 2 3]
 [4 5 6]]
Matrice di zeri: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Matrice di uni: [[1. 1.]
 [1. 1.]]
Array con step 2: [0 2 4 6 8]
Array con 10 valori equidistanti: [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


## **2. Operazioni su Array**
Esempi di operazioni matematiche e logiche su array NumPy.

In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Somma:", a + b)
print("Moltiplicazione:", a * b)
print("Radice quadrata:", np.sqrt(a))
print("Elementi > 1:", a > 1)

Somma: [5 7 9]
Moltiplicazione: [ 4 10 18]
Radice quadrata: [1.         1.41421356 1.73205081]
Elementi > 1: [False  True  True]


## **3. Indicizzazione e Slicing**
Selezione di elementi specifici da un array.

In [12]:
arr = np.array([10, 20, 30, 40])
print("Elemento in posizione 1:", arr[1])
#Ricorda che la numerazione parte da 0
print("Sottosequenza:", arr[1:3])

Elemento in posizione 1: 20
Sottosequenza: [20 30]


## **4. Manipolazione della Forma**
Cambio della forma degli array NumPy.

🔁 Differenza tra reshape e transpose:
Riorganizza la forma dell'array, mantenendo l’ordine dei dati invariato (riga per riga)


In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])
# array lineare: [1, 2, 3, 4, 5, 6]
print("Forma originale:", a.shape)
a_reshape = a.reshape(3, 2)
print("Nuova forma:", a_reshape)


Forma originale: (2, 3)
Nuova forma: [[1 2]
 [3 4]
 [5 6]]


## **5. Ordinamento e Ricerca**
Esempi di ordinamento e ricerca di valori.

In [15]:
arr = np.array([3, 1, 5, 2])
print("Array ordinato:", np.sort(arr))
print("Indici dove arr > 2:", np.where(arr > 2))

Array ordinato: [1 2 3 5]
Indici dove arr > 2: (array([0, 2]),)


## **6. Operazioni Matriciali**
Alcuni esempi di operazioni sulle matrici NumPy.

In [16]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Prodotto matriciale:", np.dot(A, B))
print("Determinante:", np.linalg.det(A))
print("Inversa:", np.linalg.inv(A))

Prodotto matriciale: [[19 22]
 [43 50]]
Determinante: -2.0000000000000004
Inversa: [[-2.   1. ]
 [ 1.5 -0.5]]


## **7. Generazione di Numeri Casuali**
Utilizzo di `numpy.random` per generare numeri casuali.

In [17]:
print("5 numeri casuali tra 0 e 1:", np.random.rand(5))
print("Matrice 3x3 con interi casuali:", np.random.randint(0, 10, size=(3, 3)))

5 numeri casuali tra 0 e 1: [0.06727452 0.54250456 0.31147133 0.07204691 0.02231536]
Matrice 3x3 con interi casuali: [[4 8 4]
 [1 9 7]
 [1 7 3]]


## **8. Esempio Interattivo**
Widget per generare array casuali.

In [18]:
size = widgets.IntText(value=5, description="Dimensione:")
button = widgets.Button(description="Genera Array Casuale")

def on_button_click(b):
    arr = np.random.randint(0, 100, size.value)
    print("Array casuale:", arr)

button.on_click(on_button_click)
display(size, button)

IntText(value=5, description='Dimensione:')

Button(description='Genera Array Casuale', style=ButtonStyle())